### ISSUE TITLE
Something error on runing build.sh

### ISSUE THREAD

**Issue by mc-zone** [chenglou/react-dash#10]
Looks like can't find this file `react-dash/src/../Contents/Resources/Documents/react/docs/class-name-manipulation.html'`
```
Converting facebook.github.io/react/css/codemirror.css... nothing to do.
Converted 175 files in 0.2 seconds.
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/mc-zone/_dev/react-dash/src/../Contents/Resources/Documents/react/docs/class-name-manipulation.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/mc-zone/_dev/react-dash/src/modifyDocsHTML.js:10:16
    at Array.forEach (native)
    at Object.<anonymous> (/Users/mc-zone/_dev/react-dash/src/modifyDocsHTML.js:7:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
Executing (default): CREATE TABLE IF NOT EXISTS `searchIndex` (`id` INTEGER, `name` VARCHAR(255), `type` VARCHAR(255), `path` VARCHAR(255));
Executing (default): PRAGMA INDEX_LIST(`searchIndex`)
Executing (default): PRAGMA INDEX_INFO(`anchor`)
Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/mc-zone/_dev/react-dash/src/../Contents/Resources/Documents/react/docs/class-name-manipulation.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/mc-zone/_dev/react-dash/src/getData.js:12:18
    at Array.map (native)
    at getData (/Users/mc-zone/_dev/react-dash/src/getData.js:9:26)
    at /Users/mc-zone/_dev/react-dash/src/index.js:27:3
    at tryCatcher (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mc-zone/_dev/react-dash/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by chenglou** [comment]
Hey! The new Dash docs for React are officially maintained by Dash now. You should be able to find them in the download section without needing to use this repo to generate your own stuff =)

**Comment by mc-zone** [comment]
Got it. @chenglou  Thank you very much for informing me :smile:
