### ISSUE TITLE
Error: Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by ilyador** [chenglou/react-dash#6]
Getting this when running `./build.sh`
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ilyo/dev/react-dash/src/modifyDocsHTML.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

**Comment by bebraw** [comment]
You need to hit `npm install` before running the script.

That said it probably wouldn't hurt if the script itself ran it.

**Comment by chenglou** [comment]
Instructions are here: https://github.com/chenglou/react-dash#instructions
You'll also need to have wget, node and sqlite3 installed. I don't think that's something the build script should handle. Plus, the instructions are pretty short =).

Btw, it's already in dash's user contribution section. You don't have to build this yourself unless you wanna submit an update.
